name: 'Common .NET Build Steps'
description: 'Shared setup, build, test, and pack steps for .NET projects'
inputs:
  solutionName:
    description: 'Name of the solution file WITHOUT the extension'
    required: true
  useSlnx:
    description: 'If true, uses .slnx solution format instead of .sln'
    required: false
    default: 'false'
  isPrimaryBuildOs:
    description: 'If true, this OS will upload release artifacts'
    required: true
  osName:
    description: 'OS name for artifact naming (e.g., linux, windows, macos)'
    required: true
  codecovToken:
    description: 'Codecov token for coverage upload'
    required: false
  sonarToken:
    description: 'Sonar token for scanning'
    required: false
  sonarProjectKey:
    description: 'Sonar project key'
    required: false
  sonarOrganisationKey:
    description: 'Sonar organisation key'
    required: false
  githubToken:
    description: 'GitHub token for Sonar'
    required: false
  virusTotalApiKey:
    description: 'VirusTotal API key'
    required: false
outputs:
  nbgvVersion:
    description: 'NBGV SemVer2 version'
    value: ${{ steps.nbgv.outputs.SemVer2 }}
  changeCommitLog:
    description: 'Changelog commit log'
    value: ${{ steps.changelog.outputs.commitLog }}
runs:
  using: 'composite'
  steps:
    - name: Setup Java 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: "a/global.json"
    
    - name: Install DotNet workloads
      shell: pwsh
      run: |
        if ($IsWindows) {
          dotnet workload install android aspire ios tvos macos maui
        } elseif ($IsMacOS) {
          dotnet workload install android aspire ios tvos macos maui
        } else {
          # Linux - skip iOS, tvOS, macOS, and maui workloads (not supported)
          dotnet workload install android aspire
        }
        dotnet workload list
      working-directory: a/src
    
    - name: Cleanup nuget local storage
      shell: pwsh
      run: |
        dotnet nuget locals all --clear
      working-directory: a/src
    
    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
        path: a
    
    - name: Install dotnet tools
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        
        $jsonPath = "../github-action-workflows/.config/dotnet-tools.json"
        
        # Validate JSON file exists
        if (-not (Test-Path $jsonPath)) {
          Write-Error "dotnet-tools.json not found at: $jsonPath"
          exit 1
        }
        
        # Parse JSON with error handling
        try {
          $json = Get-Content $jsonPath -Raw | ConvertFrom-Json
        }
        catch {
          Write-Error "Failed to parse dotnet-tools.json: $_"
          exit 1
        }
        
        foreach ($toolName in $json.tools.PSObject.Properties.Name) {
          $tool = $json.tools.$toolName
          $version = $tool.version
          Write-Output "Installing $toolName version $version globally..."
          dotnet tool install --global $toolName --version $version
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to install $toolName"
            exit $LASTEXITCODE
          }
        }
        
        Write-Output "All tools installed successfully"
      working-directory: a

    - name: Changelog
      uses: glennawatson/ChangeLog@v1
      id: changelog
      with:
        path: a
    
    - name: Prepare Artifact Directory
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path artifacts/nupkg | Out-Null
        New-Item -ItemType Directory -Force -Path artifacts/outdated | Out-Null
        New-Item -ItemType Directory -Force -Path artifacts/sbom | Out-Null
        New-Item -ItemType Directory -Force -Path artifacts/binlog | Out-Null
    
    - name: Restore Packages
      shell: pwsh
      working-directory: a/src
      run: |
        $solutionExt = if ('${{ inputs.useSlnx }}' -eq 'true') { 'slnx' } else { 'sln' }
        dotnet restore "${{ inputs.solutionName }}.$solutionExt" /bl:${{ github.workspace }}/artifacts/binlog/restore.binlog
    
    - name: Report Changelog Summary
      shell: pwsh
      run: |
        $changecommitlog = @'
        ${{ steps.changelog.outputs.commitLog }}
        '@
        $changecommitlog = $changecommitlog.Replace('"', '''')
        $lines = $changecommitlog -split "`n"
        foreach ($line in $lines) {
          Write-Output "::notice::$line"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $line
        }
    
    - name: Run Sonar Scanner begin
      if: inputs.isPrimaryBuildOs == 'true' && inputs.sonarToken != '' && inputs.sonarProjectKey != '' && inputs.sonarOrganisationKey != ''
      shell: pwsh
      working-directory: a/src
      run: |
        sonarscanner begin /k:"${{ inputs.sonarProjectKey }}" /d:sonar.login="${{ inputs.sonarToken }}" /d:sonar.host.url="https://sonarcloud.io" /o:"${{ inputs.sonarOrganisationKey }}" /d:sonar.cs.opencover.reportsPaths="${{ github.workspace }}/artifacts/unittestcoverage/coverage.xml"
    
    - name: Run Build
      id: run-build
      shell: pwsh
      working-directory: a/src
      run: |
        $env:CHANGE_COMMIT_LOG = @'
        ${{ steps.changelog.outputs.commitLog }}
        '@
        $solutionExt = if ('${{ inputs.useSlnx }}' -eq 'true') { 'slnx' } else { 'sln' }
        dotnet build "${{ inputs.solutionName }}.$solutionExt" --configuration Release --no-restore /bl:${{ github.workspace }}/artifacts/binlog/build.binlog /p:ContinuousIntegrationBuild=true
    
    - name: Run Unit Tests
      shell: pwsh
      working-directory: a/src
      run: |
        dotnet test --project ${{ inputs.solutionName }}.UnitTests/${{ inputs.solutionName }}.UnitTests.csproj --verbosity normal --configuration Release --no-build /bl:${{ github.workspace }}/artifacts/binlog/unittest.binlog --nologo --logger GitHubActions -- --coverage --coverage-output-format cobertura --coverage-output coverage.xml --long-running 10 --results-directory ${{ github.workspace }}/artifacts/unittestcoverage
    
    - name: Run Sonar Scanner end
      if: inputs.isPrimaryBuildOs == 'true' && inputs.sonarToken != '' && inputs.sonarProjectKey != '' && inputs.sonarOrganisationKey != ''
      shell: pwsh
      working-directory: a/src
      run: |
        $env:GITHUB_TOKEN = "${{ inputs.githubToken }}"
        sonarscanner end /d:sonar.login="${{ inputs.sonarToken }}"
    
    - name: Run BinLogStats for Build
      if: always() && !cancelled() && (steps.run-build.outcome == 'success' || steps.run-build.outcome == 'failure')
      shell: pwsh
      working-directory: a
      run: |
        gripe-msbuildlogstats -bl "${{ github.workspace }}/artifacts/binlog/build.binlog"
    
    - name: Report Unit Test Coverage
      shell: pwsh
      run: |
        $opencoverxmlpath = Get-ChildItem 'artifacts/unittestcoverage/coverage.xml' -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($opencoverxmlpath) {
          $xml = [xml](Get-Content $opencoverxmlpath)
          $unitTestCoverage = $xml.CoverageSession.Summary.branchCoverage
          $coverageMessage = "Unit Test Coverage: $unitTestCoverage"
          Write-Output "::notice::$coverageMessage"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $coverageMessage
        }
    
    - name: Run Integration Tests
      shell: pwsh
      working-directory: a/src
      run: |
        dotnet test --project ${{ inputs.solutionName }}.IntegrationTests/${{ inputs.solutionName }}.IntegrationTests.csproj --configuration Release --no-build --nologo /bl:../artifacts/binlog/inttest.binlog --logger "GitHubActions;verbosity=normal" -- --coverage --coverage-output-format cobertura --coverage-output coverage.xml --long-running 10 --results-directory ${{ github.workspace }}/artifacts/inttestcoverage
    
    - name: Report Integration Test Coverage
      shell: pwsh
      run: |
        $opencoverxmlpath = Get-ChildItem 'artifacts/inttestcoverage/coverage.xml' -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($opencoverxmlpath) {
          $xml = [xml](Get-Content $opencoverxmlpath)
          $intTestCoverage = $xml.CoverageSession.Summary.branchCoverage
          $coverageMessage = "Integration Test Coverage: $intTestCoverage"
          Write-Output "::notice::$coverageMessage"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $coverageMessage
        }
    
    - name: Produce Nuget Packages
      if: inputs.isPrimaryBuildOs == 'true'
      shell: pwsh
      working-directory: a/src
      run: |
        $env:CHANGE_COMMIT_LOG = @'
        ${{ steps.changelog.outputs.commitLog }}
        '@
        $solutionExt = if ('${{ inputs.useSlnx }}' -eq 'true') { 'slnx' } else { 'sln' }
        dotnet pack "${{ inputs.solutionName }}.$solutionExt" --configuration Release --no-build /bl:${{ github.workspace }}/artifacts/binlog/pack.binlog --nologo /p:PackageOutputPath=${{ github.workspace }}/artifacts/nuget /p:ContinuousIntegrationBuild=true
    
    - name: Generate SBOM
      if: inputs.isPrimaryBuildOs == 'true'
      shell: pwsh
      working-directory: a
      run: |
        sbom-tool generate -b ${{ github.workspace }}/artifacts/nuget -bc src -pn ${{ inputs.solutionName }} -pv ${{ steps.nbgv.outputs.SimpleVersion }} -ps "DHGMS Solutions" -nsb https://sbom.dhgms.com -m ${{ github.workspace }}/artifacts/sbom
    
    - name: List outdated packages
      if: inputs.isPrimaryBuildOs == 'true'
      shell: pwsh
      working-directory: a/src
      run: |
        dotnet-outdated -o ${{ github.workspace }}/artifacts/outdated/outdated.json
    
    - name: VirusTotal Monitor Scan
      if: inputs.isPrimaryBuildOs == 'true' && inputs.virusTotalApiKey != ''
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ inputs.virusTotalApiKey }}
        vt_monitor: true
        monitor_path: /ghaction-virustotal
        files: |
          ./artifacts/nuget/*.nupkg
    
    - name: Upload Code Coverage
      if: inputs.codecovToken != ''
      shell: pwsh
      run: |
        if ($IsLinux) {
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -s 'artifacts/unittestcoverage' -f '*.xml' -v -t '${{ inputs.codecovToken }}'
        } elseif ($IsMacOS) {
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -s 'artifacts/unittestcoverage' -f '*.xml' -v -t '${{ inputs.codecovToken }}'
        } elseif ($IsWindows) {
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
          .\codecov.exe -s 'artifacts/unittestcoverage' -f '*.xml' -v -t '${{ inputs.codecovToken }}'
        }
    
    - name: store binlogs
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: binlogs-${{ inputs.osName }}
        path: artifacts/binlog
    
    - name: store unit test coverage
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: unittestcoverage
        path: artifacts/unittestcoverage
        if-no-files-found: error
    
    - name: store integration test coverage
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: inttestcoverage
        path: artifacts/inttestcoverage
    
    - name: store nuget packages
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: nuget
        path: artifacts/nuget
        if-no-files-found: error
    
    - name: store omd
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: omd
        path: artifacts/omd
    
    - name: store sbom
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: sbom
        path: artifacts/sbom
    
    - name: store outdated
      if: inputs.isPrimaryBuildOs == 'true'
      uses: actions/upload-artifact@v5
      with:
        name: outdated
        path: artifacts/outdated
