# name is made short because the check path becomes really long and repeditive
name: run

on:
  workflow_call:
    inputs:
      solutionName:
        required: true
        type: string

jobs:
  omd-generation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        path: a
        persist-credentials: false

    - name: Checkout dpvreony/github-action-workflow
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: dpvreony/github-action-workflows
        path: github-action-workflows
        persist-credentials: false

    - name: Install .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
      with:
        global-json-file: "github-action-workflows/eng/omd/global.json"
        
    - name: Install dotnet tools
      run: dotnet tool restore --tool-manifest dotnet-tools.json
      working-directory:
        github-action-workflows/eng/omd

    - name: Prepare Artifact Directory
      run: |
        mkdir -p artifacts/omd

    - name: Generate OMD HTML
      run: |
        dotnet generateomd /source=${{ github.workspace }}/a/src /output=${{ github.workspace }}/artifacts/omd/index.htm /format=html
      working-directory: 
         github-action-workflows/eng/omd

    - name: store omd
      if: ${{ always() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: omd
        path: artifacts/omd
