# name is made short because the check path becomes really long and repeditive
name: run

on:
  workflow_call:
    inputs:
      solutionName:
        required: true
        type: string

jobs:
  appinspector:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: a
        persist-credentials: false

    - name: Checkout dpvreony/github-action-workflow
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: dpvreony/github-action-workflows
        path: github-action-workflows
        persist-credentials: false

    - name: Install .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        global-json-file: "github-action-workflows/eng/appinspector/global.json"
        
    - name: Install dotnet tools
      run: dotnet tool restore --tool-manifest dotnet-tools.json
      working-directory:
        github-action-workflows/eng/appinspector

    - name: Prepare Artifact Directory
      run: |
        mkdir -p artifacts/appinspector

    - name: Generate App Inspector Report
      run: |
        dotnet appinspector analyze --no-show-progress -s ${{ github.workspace }}/a/src -f html -o ${{ github.workspace }}/artifacts/appinspector/appinspector.html
      working-directory: 
         github-action-workflows/eng/appinspector

    - name: store appinspector
      if: ${{ always() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: appinspector
        path: artifacts/appinspector
