name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      actions: write
      contents: write
      deployments: read
      pages: write
      id-token: write
      pull-requests: write
      security-events: write
      packages: read
    uses: ./.github/workflows/dotnet-ci.yml
    with:
      solutionName: "Workflow"
      primary-build-mode: "linux-secondary-and-windows-primary"
      workloads: "android,ios,tvos,macos,maui"
      apiDocumentation: "DocFx"

  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/refs/tags/v1.7.9/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE} -color
        shell: bash
        env:
          STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}

  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d
